# build stage
FROM golang:1.22-alpine as build

WORKDIR /root/app

COPY ./libs ./libs/
COPY ./client ./client/

WORKDIR /root/app/client

RUN go mod download && go mod verify

# RUN go build -v -o /usr/local/bin/mt-client ./main.go
RUN go build -v -o /mt-client ./main.go

# runtime stage
FROM alpine

WORKDIR /usr/local/bin

COPY --from=build /mt-client .

WORKDIR /root/app

COPY ./client/testfiles/ ./testfiles/

ENTRYPOINT ["ash"]
