services:
  goserver:
    build: .
    container_name: zama-server-stage
    environment:
      - USE_ENVVAR=true             
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
    ports:
      - "8080:8080"
version: "3.8"
