services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile.server
    env_file: .env
    container_name: merkle-tree-file-server
    environment:
      - USE_ENVVAR=true
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=${PORT}
      - MAX_BULK_UPLOAD_SIZE=33554432 # 32MB
      - MAX_UPLOAD_FILE_SIZE=2097152 # 2MB
      - UPLOAD_FOLDER=./uploads

    ports:
      - "${PORT}:${PORT}"
  client:
    depends_on:
      - server
    build: 
      context: .
      dockerfile: ./Dockerfile.client
    container_name: mt-client
    stdin_open: true
    tty: true
    environment:
      - DEFAULT_STORAGE_FOLDER=./storage
      - DEFAULT_DOWNLOAD_FOLDER=./downloads
      - DEFAULT_UPLOAD_FOLDER=./testfiles
      - SERVER_URL=http://172.17.0.1:${PORT}
version: "3.8"
