host: localhost:8080
info:
  contact: {}
  description: HTTP File Server with Merkle Tree to ensure that the downloaded data
    is not tampered
  title: File Server with Merkle Tree
  version: "1.0"
paths:
  /files:
    get:
      consumes:
      - application/json
      description: List files
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: List
      tags:
      - Files
    post:
      consumes:
      - multipart/form-data
      description: Bulk Upload all files in a given folder and create merkle tree
      parameters:
      - collectionFormat: csv
        description: files to upload
        in: formData
        items:
          type: file
        name: file
        required: true
        type: array
      produces:
      - text/plain
      responses:
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Bulk Upload
      tags:
      - Files
  /files/{filename}:
    get:
      consumes:
      - application/json
      description: Download By Name
      parameters:
      - description: File Name
        format: string
        in: path
        name: filename
        required: true
        type: string
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Download
      tags:
      - Files
swagger: "2.0"
